s1=input("Enter first string:")
s2=input("Enter second string")
print("Concatenated string is:",s1+s2)
print(s1.upper())                                
print(s2.lower())                               
print(s1[1])                                     
print(s2[2:5])                                  
print(s1==s2)                                    
print(len(s1))                                   
